using Microsoft.Data.SqlClient;using ModernWMS.Backend.Models;using System.Data;namespace ModernWMS.Backend.Repositories;public class SqlLocationRepository:ILocationRepository{private readonly string _conn;public SqlLocationRepository(IConfiguration cfg){_conn=cfg.GetConnectionString("LegacySqlDB")??throw new InvalidOperationException();}public async Task<(IEnumerable<Location> Locations, int TotalCount)> GetAllAsync(int page, int pageSize, string facilityId){var lst=new List<Location>();int total=0;using var c=new SqlConnection(_conn);await c.OpenAsync();
// Get total count
using(var cmdCount=new SqlCommand("SELECT COUNT(*) FROM LOCATION WHERE STATUS!='I' AND FACILITY=@fac",c)){cmdCount.Parameters.AddWithValue("@fac",facilityId);total=(int)await cmdCount.ExecuteScalarAsync();}
// Get paginated data
using var cmd=new SqlCommand("SELECT*FROM LOCATION WHERE STATUS!='I' AND FACILITY=@fac ORDER BY LOCATION OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY",c);cmd.Parameters.AddWithValue("@fac",facilityId);cmd.Parameters.AddWithValue("@offset",(page-1)*pageSize);cmd.Parameters.AddWithValue("@limit",pageSize);using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())lst.Add(Map(r));return(lst,total);}public async Task<Location?>GetByIdAsync(string id){using var c=new SqlConnection(_conn);await c.OpenAsync();using var cmd=new SqlCommand("SELECT*FROM LOCATION WHERE LOCATION=@id",c);cmd.Parameters.AddWithValue("@id",id);using var r=await cmd.ExecuteReaderAsync();if(await r.ReadAsync())return Map(r);return null;}public async Task<string>CreateAsync(Location l){using var c=new SqlConnection(_conn);await c.OpenAsync();using var cmd=new SqlCommand("INSERT INTO LOCATION(LOCATION,FACILITY,ZONE,SECTION,LOCATIONTYPE,STATUS,MAXWEIGHT,MAXVOLUME,LASTUPDATE,LASTUSER)VALUES(@id,@fac,@zone,@sec,@type,@st,@wgt,@vol,GETDATE(),@usr)",c);cmd.Parameters.AddWithValue("@id",l.Id);cmd.Parameters.AddWithValue("@fac",l.FacilityId);cmd.Parameters.AddWithValue("@zone",(object?)l.ZoneId??DBNull.Value);cmd.Parameters.AddWithValue("@sec",(object?)l.SectionId??DBNull.Value);cmd.Parameters.AddWithValue("@type",(object?)l.LocationType??DBNull.Value);cmd.Parameters.AddWithValue("@st",l.Status);cmd.Parameters.AddWithValue("@wgt",(object?)l.MaxWeight??DBNull.Value);cmd.Parameters.AddWithValue("@vol",(object?)l.MaxVolume??DBNull.Value);cmd.Parameters.AddWithValue("@usr","SYSTEM");await cmd.ExecuteNonQueryAsync();return l.Id;}public async Task<bool>UpdateAsync(Location l){using var c=new SqlConnection(_conn);await c.OpenAsync();using var cmd=new SqlCommand("UPDATE LOCATION SET FACILITY=@fac,ZONE=@zone,SECTION=@sec,LOCATIONTYPE=@type,STATUS=@st,MAXWEIGHT=@wgt,MAXVOLUME=@vol,LASTUPDATE=GETDATE(),LASTUSER=@usr WHERE LOCATION=@id",c);cmd.Parameters.AddWithValue("@id",l.Id);cmd.Parameters.AddWithValue("@fac",l.FacilityId);cmd.Parameters.AddWithValue("@zone",(object?)l.ZoneId??DBNull.Value);cmd.Parameters.AddWithValue("@sec",(object?)l.SectionId??DBNull.Value);cmd.Parameters.AddWithValue("@type",(object?)l.LocationType??DBNull.Value);cmd.Parameters.AddWithValue("@st",l.Status);cmd.Parameters.AddWithValue("@wgt",(object?)l.MaxWeight??DBNull.Value);cmd.Parameters.AddWithValue("@vol",(object?)l.MaxVolume??DBNull.Value);cmd.Parameters.AddWithValue("@usr","SYSTEM");return await cmd.ExecuteNonQueryAsync()>0;}    public async Task<bool> DeleteAsync(string id)
    {
        using var c = new SqlConnection(_conn);
        await c.OpenAsync();
        using var cmd = new SqlCommand("DELETE FROM LOCATION WHERE LOCATION = @id", c);
        cmd.Parameters.AddWithValue("@id", id);
        return await cmd.ExecuteNonQueryAsync() > 0;
    }private Location Map(IDataRecord r)=>new Location{Id=r["LOCATION"]?.ToString()??"",FacilityId=r["FACILITY"]?.ToString()??"",ZoneId=r["ZONE"]?.ToString(),SectionId=r["SECTION"]?.ToString(),LocationType=r["LOCATIONTYPE"]?.ToString(),Status=r["STATUS"]?.ToString()??"A",MaxWeight=r["MAXWEIGHT"]!=DBNull.Value?Convert.ToDecimal(r["MAXWEIGHT"]):null,MaxVolume=r["MAXVOLUME"]!=DBNull.Value?Convert.ToDecimal(r["MAXVOLUME"]):null,LastUpdate=r["LASTUPDATE"]!=DBNull.Value?Convert.ToDateTime(r["LASTUPDATE"]):DateTime.Now,LastUser=r["LASTUSER"]?.ToString()??"SYSTEM"};}
