
-- Rename EMPLOYEE table to USERS if it exists
IF OBJECT_ID('EMPLOYEE', 'U') IS NOT NULL
BEGIN
    EXEC sp_rename 'EMPLOYEE', 'USERS';
END
GO

-- Rename column EMPLOYEEID to USERID for consistency IF IT EXISTS with old name
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'EMPLOYEEID')
BEGIN
    EXEC sp_rename 'USERS.EMPLOYEEID', 'USERID', 'COLUMN';
END
GO

-- Create ROLES table
IF OBJECT_ID('ROLES', 'U') IS NULL
BEGIN
    CREATE TABLE ROLES (
        ROLEID NVARCHAR(50) PRIMARY KEY,
        DESCRIPTION NVARCHAR(255)
    );
END
GO

-- Seed ROLES (Idempotent)
IF NOT EXISTS (SELECT 1 FROM ROLES WHERE ROLEID = 'ADMIN')
    INSERT INTO ROLES (ROLEID, DESCRIPTION) VALUES ('ADMIN', 'Full system access');
IF NOT EXISTS (SELECT 1 FROM ROLES WHERE ROLEID = 'OPERATOR')
    INSERT INTO ROLES (ROLEID, DESCRIPTION) VALUES ('OPERATOR', 'Standard warehouse operations');
IF NOT EXISTS (SELECT 1 FROM ROLES WHERE ROLEID = 'VIEWER')
    INSERT INTO ROLES (ROLEID, DESCRIPTION) VALUES ('VIEWER', 'Read-only access');
IF NOT EXISTS (SELECT 1 FROM ROLES WHERE ROLEID = 'SUPERVISOR')
    INSERT INTO ROLES (ROLEID, DESCRIPTION) VALUES ('SUPERVISOR', 'Oversees operations, can approve adjustments');
IF NOT EXISTS (SELECT 1 FROM ROLES WHERE ROLEID = 'INVENTORY')
    INSERT INTO ROLES (ROLEID, DESCRIPTION) VALUES ('INVENTORY', 'Inventory management and counting');
GO

-- Create USER_ROLES table
IF OBJECT_ID('USER_ROLES', 'U') IS NULL
BEGIN
    CREATE TABLE USER_ROLES (
        USERID VARCHAR(20),  -- Matches USERS.USERID
        ROLEID NVARCHAR(50),
        PRIMARY KEY (USERID, ROLEID),
        FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE,
        FOREIGN KEY (ROLEID) REFERENCES ROLES(ROLEID) ON DELETE CASCADE
    );
END
GO

-- Create USER_FACILITIES table for granular access
IF OBJECT_ID('USER_FACILITIES', 'U') IS NULL
BEGIN
    CREATE TABLE USER_FACILITIES (
        USERID VARCHAR(20), -- Matches USERS.USERID
        FACILITYID NVARCHAR(50), -- Assuming Facility ID is NVARCHAR(50) or matching logical type
        PRIMARY KEY (USERID, FACILITYID),
        FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
    );
END
GO

-- Create USER_CUSTOMERS table for granular access
IF OBJECT_ID('USER_CUSTOMERS', 'U') IS NULL
BEGIN
    CREATE TABLE USER_CUSTOMERS (
        USERID VARCHAR(20), -- Matches USERS.USERID
        CUSTOMERID NVARCHAR(50), -- Assuming Customer ID is NVARCHAR(50)
        PRIMARY KEY (USERID, CUSTOMERID),
        FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
    );
END
GO

-- Assign ADMIN role to existing 'admin' user if exists
IF EXISTS (SELECT 1 FROM USERS WHERE USERID = 'admin')
BEGIN
    IF NOT EXISTS (SELECT 1 FROM USER_ROLES WHERE USERID = 'admin' AND ROLEID = 'ADMIN')
    BEGIN
        INSERT INTO USER_ROLES (USERID, ROLEID) VALUES ('admin', 'ADMIN');
    END
END
GO
