
-- Supplemental Permissions for Role management
INSERT INTO PERMISSIONS (PERMISSIONID, ENTITY, OPERATION, DESCRIPTION) 
VALUES ('ROLE_READ', 'ROLE', 'READ', 'Read access to roles and their permissions');

INSERT INTO PERMISSIONS (PERMISSIONID, ENTITY, OPERATION, DESCRIPTION) 
VALUES ('ROLE_UPDATE', 'ROLE', 'UPDATE', 'Assign permissions to roles');

-- Assign to ADMIN
INSERT INTO ROLE_PERMISSIONS (ROLEID, PERMISSIONID)
SELECT 'ADMIN', 'ROLE_READ' WHERE NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS WHERE ROLEID = 'ADMIN' AND PERMISSIONID = 'ROLE_READ');

INSERT INTO ROLE_PERMISSIONS (ROLEID, PERMISSIONID)
SELECT 'ADMIN', 'ROLE_UPDATE' WHERE NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS WHERE ROLEID = 'ADMIN' AND PERMISSIONID = 'ROLE_UPDATE');
GO
