
-- Supplemental Permissions for AI
INSERT INTO PERMISSIONS (PERMISSIONID, ENTITY, OPERATION, DESCRIPTION) 
VALUES ('AI_READ', 'AI', 'READ', 'Access to AI forecasting and optimization');

-- Assign to ADMIN
INSERT INTO ROLE_PERMISSIONS (ROLEID, PERMISSIONID)
SELECT 'ADMIN', 'AI_READ' WHERE NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS WHERE ROLEID = 'ADMIN' AND PERMISSIONID = 'AI_READ');

-- Assign to OPERATOR
INSERT INTO ROLE_PERMISSIONS (ROLEID, PERMISSIONID)
SELECT 'OPERATOR', 'AI_READ' WHERE NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS WHERE ROLEID = 'OPERATOR' AND PERMISSIONID = 'AI_READ');
GO
