-- Drop existing PK on ITEMGROUP
DECLARE @pkname nvarchar(255)
SELECT @pkname = name FROM sys.key_constraints WHERE type = 'PK' AND parent_object_id = OBJECT_ID('ITEMGROUP');
IF @pkname IS NOT NULL
    EXEC('ALTER TABLE ITEMGROUP DROP CONSTRAINT ' + @pkname);

-- Update NULLs
UPDATE ITEMGROUP SET CUSTID = 'UNKNOWN' WHERE CUSTID IS NULL;

-- Alter CUSTID to NOT NULL (Standardize length to 30 as in Item)
ALTER TABLE ITEMGROUP ALTER COLUMN CUSTID nvarchar(30) NOT NULL;

-- Add new Composite PK
ALTER TABLE ITEMGROUP ADD CONSTRAINT PK_ITEMGROUP_CUST PRIMARY KEY CLUSTERED (ITEMGROUP ASC, CUSTID ASC);
