-- Migration for ZONE table
DECLARE @pkname_zone nvarchar(255)
SELECT @pkname_zone = name FROM sys.key_constraints WHERE type = 'PK' AND parent_object_id = OBJECT_ID('ZONE');
IF @pkname_zone IS NOT NULL
    EXEC('ALTER TABLE ZONE DROP CONSTRAINT ' + @pkname_zone);

UPDATE ZONE SET FACILITY = 'UNKNOWN' WHERE FACILITY IS NULL OR FACILITY = '';
ALTER TABLE ZONE ALTER COLUMN FACILITY nvarchar(30) NOT NULL;
ALTER TABLE ZONE ADD CONSTRAINT PK_ZONE_FAC PRIMARY KEY CLUSTERED (ZONE ASC, FACILITY ASC);

-- Migration for SECTION table
DECLARE @pkname_section nvarchar(255)
SELECT @pkname_section = name FROM sys.key_constraints WHERE type = 'PK' AND parent_object_id = OBJECT_ID('SECTION');
IF @pkname_section IS NOT NULL
    EXEC('ALTER TABLE SECTION DROP CONSTRAINT ' + @pkname_section);

UPDATE SECTION SET FACILITY = 'UNKNOWN' WHERE FACILITY IS NULL OR FACILITY = '';
ALTER TABLE SECTION ALTER COLUMN FACILITY nvarchar(30) NOT NULL;
ALTER TABLE SECTION ADD CONSTRAINT PK_SECTION_FAC PRIMARY KEY CLUSTERED (SECTION ASC, FACILITY ASC);
