-- MS SQL Server Setup Script for ModernWMS
-- Create the necessary tables in the target SQL Server database

-- 1. FACILITY Table
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'FACILITY')
BEGIN
    CREATE TABLE FACILITY (
        FACILITY VARCHAR(3) PRIMARY KEY,
        NAME VARCHAR(40),
        ADDR1 VARCHAR(40),
        ADDR2 VARCHAR(40),
        CITY VARCHAR(30),
        STATE VARCHAR(2),
        POSTALCODE VARCHAR(10),
        COUNTRYCODE VARCHAR(2),
        PHONE VARCHAR(20),
        FAX VARCHAR(20),
        EMAIL VARCHAR(100),
        MANAGER VARCHAR(40),
        FACILITYSTATUS CHAR(1) DEFAULT 'A',
        REMITNAME VARCHAR(40),
        REMITADDR1 VARCHAR(40),
        REMITCITY VARCHAR(30),
        REMITSTATE VARCHAR(2),
        REMITPOSTALCODE VARCHAR(10),
        TASKLIMIT INT,
        XDOCKLOC VARCHAR(15),
        FACILITYGROUP VARCHAR(15),
        USE_LOCATION_CHECKDIGIT CHAR(1) DEFAULT 'N',
        RESTRICT_PUTAWAY CHAR(1) DEFAULT 'N',
        WORKSUNDAY_IN CHAR(1) DEFAULT 'N',
        WORKMONDAY_IN CHAR(1) DEFAULT 'Y',
        WORKTUESDAY_IN CHAR(1) DEFAULT 'Y',
        WORKWEDNESDAY_IN CHAR(1) DEFAULT 'Y',
        WORKTHURSDAY_IN CHAR(1) DEFAULT 'Y',
        WORKFRIDAY_IN CHAR(1) DEFAULT 'Y',
        WORKSATURDAY_IN CHAR(1) DEFAULT 'N',
        LASTUPDATE DATETIME DEFAULT GETDATE(),
        LASTUSER VARCHAR(20) DEFAULT 'SYSTEM'
    );
END

-- 2. PLATE Table
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'PLATE')
BEGIN
    CREATE TABLE PLATE (
        LPID VARCHAR(20) PRIMARY KEY,
        ITEM VARCHAR(20) NOT NULL,
        CUSTID VARCHAR(15),
        FACILITY VARCHAR(3) REFERENCES FACILITY(FACILITY),
        LOCATION VARCHAR(15),
        STATUS VARCHAR(1) DEFAULT 'A',
        QUANTITY DECIMAL(18, 4) DEFAULT 0,
        UNITOFMEASURE VARCHAR(10),
        LOTNUMBER VARCHAR(20),
        SERIALNUMBER VARCHAR(40),
        TYPE VARCHAR(10),
        HOLDREASON VARCHAR(50),
        INVENTORYCLASS VARCHAR(10),
        WEIGHT DECIMAL(10, 2),
        PO VARCHAR(20),
        PARENTLPID VARCHAR(20),
        CREATIONDATE DATETIME DEFAULT GETDATE(),
        MANUFACTUREDATE DATETIME,
        EXPIRATIONDATE DATETIME,
        LASTUPDATE DATETIME DEFAULT GETDATE(),
        LASTUSER VARCHAR(20) DEFAULT 'SYSTEM'
    );
END

-- 3. INVENTORY Table (For legacy migration support)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'INVENTORY')
BEGIN
    CREATE TABLE INVENTORY (
        ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        SKU VARCHAR(20) NOT NULL,
        QUANTITY INT DEFAULT 0,
        LOCATIONCODE VARCHAR(20),
        FACILITYID VARCHAR(3) REFERENCES FACILITY(FACILITY)
    );
END
