-- Add FK constraints for Restrict Delete (Default is NO ACTION)

-- 1. ZONE -> FACILITY
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_ZONE_FACILITY')
BEGIN
    ALTER TABLE ZONE
    ADD CONSTRAINT FK_ZONE_FACILITY FOREIGN KEY (FACILITY)
    REFERENCES FACILITY (FACILITY);
END

-- 2. SECTION -> ZONE (Composite Key)
-- Ensure columns match types. SECTION(FACILITY, ZONE) -> ZONE(FACILITY, ZONE)
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_SECTION_ZONE')
BEGIN
    -- Only add if data is valid (optional cleanup, but let's assume valid or let it fail so user knows)
    ALTER TABLE SECTION
    ADD CONSTRAINT FK_SECTION_ZONE FOREIGN KEY (FACILITY, ZONE)
    REFERENCES ZONE (FACILITY, ZONE);
END

-- 3. LOCATION -> FACILITY
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_LOCATION_FACILITY')
BEGIN
    ALTER TABLE LOCATION
    ADD CONSTRAINT FK_LOCATION_FACILITY FOREIGN KEY (FACILITY)
    REFERENCES FACILITY (FACILITY);
END

-- 4. LOCATION -> ZONE (Composite Key)
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_LOCATION_ZONE')
BEGIN
    ALTER TABLE LOCATION
    ADD CONSTRAINT FK_LOCATION_ZONE FOREIGN KEY (FACILITY, ZONE)
    REFERENCES ZONE (FACILITY, ZONE);
END

-- 5. LOCATION -> SECTION (Composite Key)
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_LOCATION_SECTION')
BEGIN
    ALTER TABLE LOCATION
    ADD CONSTRAINT FK_LOCATION_SECTION FOREIGN KEY (FACILITY, SECTION)
    REFERENCES SECTION (FACILITY, SECTION);
END

-- 6. ITEMGROUP -> CUSTOMER
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_ITEMGROUP_CUSTOMER')
BEGIN
    ALTER TABLE ITEMGROUP
    ADD CONSTRAINT FK_ITEMGROUP_CUSTOMER FOREIGN KEY (CUSTID)
    REFERENCES CUSTOMER (CUSTID);
END

-- 7. ITEM -> CUSTOMER
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_ITEM_CUSTOMER')
BEGIN
    ALTER TABLE ITEM
    ADD CONSTRAINT FK_ITEM_CUSTOMER FOREIGN KEY (CUSTID)
    REFERENCES CUSTOMER (CUSTID);
END

-- 8. ITEM -> ITEMGROUP
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_ITEM_ITEMGROUP')
BEGIN
    -- This assumes ITEMGROUP PK is (CUSTID, ITEMGROUP)
    ALTER TABLE ITEM
    ADD CONSTRAINT FK_ITEM_ITEMGROUP FOREIGN KEY (CUSTID, ITEMGROUP)
    REFERENCES ITEMGROUP (CUSTID, ITEMGROUP);
END

-- 9. PLATE -> CUSTOMER
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_PLATE_CUSTOMER')
BEGIN
    ALTER TABLE PLATE
    ADD CONSTRAINT FK_PLATE_CUSTOMER FOREIGN KEY (CUSTID)
    REFERENCES CUSTOMER (CUSTID);
END

-- 10. PLATE -> FACILITY
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_PLATE_FACILITY')
BEGIN
    ALTER TABLE PLATE
    ADD CONSTRAINT FK_PLATE_FACILITY FOREIGN KEY (FACILITY)
    REFERENCES FACILITY (FACILITY);
END

-- 11. PLATE -> LOCATION (Composite: FACILITY + LOCATION)
-- Note: PLATE has LOCATION column. FACILITY column. Use them.
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_PLATE_LOCATION')
BEGIN
    ALTER TABLE PLATE
    ADD CONSTRAINT FK_PLATE_LOCATION FOREIGN KEY (FACILITY, LOCATION)
    REFERENCES LOCATION (FACILITY, LOCATION);
END

-- 12. PLATE -> ITEM
-- Assuming ITEM PK is ITEM (SKU). If Composite (CUSTID, ITEM), use that.
-- Let's check ITEM PK. Based on ItemRepo, it seems ITEM is unique ID.
-- But safest is just ITEM FK if likely.
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_PLATE_ITEM')
BEGIN
    ALTER TABLE PLATE
    ADD CONSTRAINT FK_PLATE_ITEM FOREIGN KEY (ITEM)
    REFERENCES ITEM (ITEM);
END
