-- Decouple LOCATION from ZONE directly (Hierarchy should be Zone -> Section -> Location)
-- 1. Drop FK_LOCATION_ZONE if it exists
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_LOCATION_ZONE')
BEGIN
    ALTER TABLE LOCATION DROP CONSTRAINT FK_LOCATION_ZONE;
END

-- Verify FK_SECTION_ZONE exists (Zone -> Section)
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_SECTION_ZONE')
BEGIN
    ALTER TABLE SECTION
    ADD CONSTRAINT FK_SECTION_ZONE FOREIGN KEY (FACILITY, ZONE)
    REFERENCES ZONE (FACILITY, ZONE);
END

-- Verify FK_LOCATION_SECTION exists (Section -> Location)
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_LOCATION_SECTION')
BEGIN
    ALTER TABLE LOCATION
    ADD CONSTRAINT FK_LOCATION_SECTION FOREIGN KEY (FACILITY, SECTION)
    REFERENCES SECTION (FACILITY, SECTION);
END
