-- Add Synapse fields to ITEMGROUP
ALTER TABLE ITEMGROUP ADD BaseUOM NVARCHAR(10) DEFAULT 'EA';
ALTER TABLE ITEMGROUP ADD TrackLotNumber BIT DEFAULT 0;
ALTER TABLE ITEMGROUP ADD TrackSerialNumber BIT DEFAULT 0;
ALTER TABLE ITEMGROUP ADD TrackExpirationDate BIT DEFAULT 0;
ALTER TABLE ITEMGROUP ADD TrackManufactureDate BIT DEFAULT 0;
ALTER TABLE ITEMGROUP ADD IsHazardous BIT DEFAULT 0;
ALTER TABLE ITEMGROUP ADD HazardClass NVARCHAR(20);
ALTER TABLE ITEMGROUP ADD UNNumber NVARCHAR(20);
ALTER TABLE ITEMGROUP ADD PackingGroup NVARCHAR(10);
ALTER TABLE ITEMGROUP ADD CommodityCode NVARCHAR(20);
ALTER TABLE ITEMGROUP ADD CountryOfOrigin NVARCHAR(50);
ALTER TABLE ITEMGROUP ADD VelocityClass NVARCHAR(1);

-- Add Synapse fields to ITEM
ALTER TABLE ITEM ADD CommodityCode NVARCHAR(20);
ALTER TABLE ITEM ADD CountryOfOrigin NVARCHAR(50);
ALTER TABLE ITEM ADD VelocityClass NVARCHAR(1);
ALTER TABLE ITEM ADD Ti INT;
ALTER TABLE ITEM ADD Hi INT;

-- Add Synapse fields to CUSTOMER
ALTER TABLE CUSTOMER ADD AllowPartialShipment BIT DEFAULT 1;
ALTER TABLE CUSTOMER ADD AllowOverage BIT DEFAULT 0;
ALTER TABLE CUSTOMER ADD OverageTolerance DECIMAL(5,2) DEFAULT 0;
ALTER TABLE CUSTOMER ADD DefaultTrackLot BIT DEFAULT 0;
ALTER TABLE CUSTOMER ADD DefaultTrackSerial BIT DEFAULT 0;
ALTER TABLE CUSTOMER ADD DefaultTrackExpDate BIT DEFAULT 0;
ALTER TABLE CUSTOMER ADD DefaultTrackMfgDate BIT DEFAULT 0;
